/**
 * This code was generated by Builder.io.
 */
export interface Property {
  id: number;
  name: string;
  address: string;
  details: string;
  size: string;
  price: string;
  listing: string;
  image: string;
}
